# Generated by Django 5.2.11 on 2026-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsession_is_locked_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='trick',
            field=models.TextField(blank=True, null=True),
        ),
    ]
